version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: devpoker-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - devpoker-network

  adminer:
    image: adminer
    container_name: devpoker-adminer
    ports:
      - 8032:8080
    networks:
      - devpoker-network

  db:
    image: postgres:13
    container_name: devpoker-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - devpoker-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - devpoker-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: devpoker-keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    networks:
      - devpoker-network

  gateway:
    image: devpoker-gateway
    container_name: devpoker-gateway
    build:
      context: ../gateway
      dockerfile: Dockerfile
    environment:
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_MANAGEMENT_PORT=15672
    ports:
      - 8000:8000
    networks:
      - devpoker-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  estimate:
    image: devpoker-estimate
    container_name: devpoker-estimate
    build:
      context: ../estimate
      dockerfile: Dockerfile
    environment:
      - RABBIT_PASSWORD=guest
      - RABBIT_USER=guest
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_MANAGEMENT_PORT=15672
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=estimate
    networks:
      - devpoker-network
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  devpoker-network:
    name: devpoker-network
    external: false

volumes:
  devpoker-db-volume:
    name: devpoker-db-volume
